version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"    
  mysql:
    container_name: database
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_ROOT_HOST: "%"
